[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sstai"
version = "0.1.0"
description = "Sahand True AI core library"
requires-python = ">=3.8"
dependencies = [
    "fastapi",
    "uvicorn",
    "numpy",
]
